# Generated by Django 5.2.7 on 2025-10-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foyer',
            name='nb_pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('tresorier', 'Trésorier'), ('membre', 'Membre'), ('junior', 'Junior'), ('invite', 'Invité'), ('superviseur', 'Superviseur'), ('observateur', 'Observateur')], default='membre', max_length=20),
        ),
    ]
