# Generated by Django 5.2.7 on 2025-10-28 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0002_foyer_nb_pieces_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('tresorier', 'Trésorier'), ('membre', 'Membre'), ('junior', 'Junior'), ('invite', 'Invité'), ('superviseur', 'Superviseur'), ('observateur', 'Observateur')], default='membre', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.utilisateur')),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison_app.foyer')),
            ],
        ),
    ]
