# Generated by Django 5.2.7 on 2025-10-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0005_alter_utilisateur_managers_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='id_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maison_app.piece'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(blank=True, choices=[('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], max_length=20, null=True),
        ),
    ]
