# Generated by Django 5.2.7 on 2025-10-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maison_app', '0006_tache_id_piece_alter_tache_date_limite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='id_foyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='maison_app.foyer'),
            preserve_default=False,
        ),
    ]
